### ISSUE TITLE
Test Level Rules

### ISSUE THREAD

**Issue by MiikkaSolmela** [MarketSquare/robotframework-style-guide#16]
Rules to describe:
- Max. number of KW calls in a test
- review rules in Robocop and robotidy
- Naming test cases to be readable in logs- longer or complex can be hard to read
- best practices for naming tests and test files for better logs

**Comment by guidodemmenie** [comment]
Split up:
1. Naming testcases and complexity of them -> #68 
2. Number of KW in keyword -> #67
