### ISSUE TITLE
Arguments File

### ISSUE THREAD

**Issue by kstine** [MarketSquare/robotframework-style-guide#30]
Should we have guidance for format of an arguments file.

Or should this be a guide not style guide?

**Comment by guidodemmenie** [comment]
@kstine do you mean [argument files](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#argument-file-syntax) ?

In that case I believe this is "Manual" material, not styleguide.

**Comment by guidodemmenie** [comment]
During StyleGuide session: This is not part of the testsuites or resources files and thus not part of the style-guide scope.
