### ISSUE TITLE
RF Doc style Proposal

### ISSUE THREAD

**Issue by kstine** [MarketSquare/robotframework-style-guide#5]
Keywords - Documentation (Proposed)
Purpose: To  leverage the VSCode Extension "Robot Framework Language Server" ability to preview Keyword Documentation.

After reviewing a few docstring styles, the one that proved most adaptable to Robot Framework was from Google: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
It goes without saying that any part of Robot Framework that is Python should follow the docstring guidance from the PEP8 Python Style Guide. 

The Bare Minimum
Documentation should be always listed for every keyword and for every "*** Settings ***" section within a resource or robot file.

The minimum string used should be "None".

"None" is reserved for the case where the keyword is self defining.

"None" used for a resource or robot file is not acceptable.

Resource and Robot Files
Provide a few lines describing what the file is for.
It can be a simple as New Calls Page Object or REST API Endpoint Parsing Keyword Library
Keywords- No arguments, no returns, no assertions
Provide a one or two lines description of what the keyword does.

The description should be descriptive-style (Fetches rows from a Bigtable.) rather than imperative-style (Fetch rows from a Bigtable.).

Keywords- Arguments
Basic argument documentation syntax:

```
This Is A Keyword With Arguments
  [Documentation]  This keyword does things.
  ...
  ...  Args:
  ...  - i_am_an_argument (str): required
  ...  - dict_var (dict):
  ...      required, expected keys [key1, key2, key3]
  ...  - i_am_an_arg_with_default (str): defaults to [None]
  ...  - a_var_assigned_to_a_var (int):  defaults to [$GLOBAL_INT_VAR]
  [Arguments]  ${i_am_an_argument}  ${dict_var}  ${i_am_an_arg_with_default}=${NONE}. ${a_var_assigned_to_a_var}=${GLOBAL_INT_VAR}
```

As you can see there is an general pattern.
•	Initial Documentation line(s)
•	Blank return line
•	"Args:" header
•	List of the arguments starting with a "- " (translates to a bullet point in the intelligent description popup)
•	An argument line has: name of argument without scalar notation, type in parens, colon, description
•	Typing is the same as standard Python typing.
•	Descriptions usually start with whether the argument is required or defaulted (optional)
•	If needed the argument description can be placed below the arg line, and indented.
•	When optional the default value is put in a set of brackets.

Keywords- Returns
Basic return documentation syntax:
```
This Is A Keyword With Arguments
  [Documentation]  This keyword does things.
  ...
  ...  Returns:
  ...  - (str): returns a string
```
As you can see, the syntax is similar.
•	Initial Documentation line(s) or an "Args" section
•	Blank return line
•	"Returns:" header
•	List of the returns starting with a "- " (translates to a bullet point in the intelligent description popup)
•	An returns line has: type in parens, colon, description
•	Typing is the same as standard Python typing.
•	Descriptions are as needed.

If a Keyword creates a GLOBAL, SUITE, or TEST variable the pattern changes slightly:
```
Create The Global Int Variable
  [Documentation]  Creates a global int variable
  ...
  ...  Returns:
  ...  - GLOBAL_INT_VAR (int): GLOBAL
```

•	The pattern is changed to include the constant cased variable without scalar notation and the scope listed in all caps in the beginning of the description.

Keywords- Assertions
This section is only for keywords that have an assertion type keyword (i.e. Should...)

```
Verify That Normalcy Has Been Attained
  [Documentation]  Is it normal?
  ...
  ...  Asserts:
  ...  - Should Be Equal: established that things are equal
```
The syntax provides quick clarity on what the keyword is asserting.
•	Initial Documentation line(s) or an "Args" section or "Returns" section
•	Blank return line
•	"Asserts:" header
•	List of the returns starting with a "- " (translates to a bullet point in the intelligent description popup)
•	An asserts line has: Name of Asserting Keyword, colon, description
•	Description should be as detailed as needed

**Comment by bhirsz** [comment]
I do like Google-style docs and it's also something I had in mind when I worked on idea for documentation transformer: https://github.com/MarketSquare/robotframework-tidy/issues/311

Your proposal is more detailed and I need to analyse it thoroughly later but I already see it'll be possible to automate a lot of the documentation creation with the help of the Robotidy. There are some differences as compared to my idea but it can been worked on (ie. robot variable name without ${}). Can I assume that anything that don't have default value and is not *arg/**kwarg will get 'required' label? (this will be controllable in the template, if the users don't want it they could modify basic template and remove that part).

**Comment by bhirsz** [comment]
Should we use 'Args' or rather go with full name 'Arguments'? I'm not sure if there are extra benefit over using shorter name especially if the setting name is [Arguments]. Though it could provide visual difference from the setting itself.

**Comment by bhirsz** [comment]
It's really interesting idea (and useful for documentation purposes) :
```
Returns:
... - GLOBAL_INT_VAR (int): GLOBAL 
```
But I'm not sure if we should use 'Returns' here (as the keyword could not return anything and it would be misleading) . Maybe some new name like 'Sets', 'Globals' or similar?

**Comment by kstine** [comment]
I did some stackoverflow poking around (always dangerous) and found this to be an interesting solution. Maybe not directly related. [https://stackoverflow.com/questions/64796801/documenting-class-level-variables-in-python]

Otherwise using:
```
Sets:
...  - GLOBAL_INT_VAR (int): GLOBAL 
```
Does seem to fit better.

**Comment by kstine** [comment]
> Should we use 'Args' or rather go with full name 'Arguments'? I'm not sure if there are extra benefit over using shorter name especially if the setting name is [Arguments]. Though it could provide visual difference from the setting itself.

I am used to python lingo- it is easier to type Args, but if Tidy were autocreating it then it can be Arguments.

Args does have the benefit of channeling your inner pirate.

**Comment by kstine** [comment]
What about Keywords that require a scoped variable? So instead of an argument it would be a variable of TEST, SUITE, GLOBAL scope. I defaulted these to Args, but maybe these variables receive special documentation.

**Comment by MoreFamed** [comment]
```
Verify That Normalcy Has Been Attained
  [Documentation]  Is it normal?
  ...
  ...  Asserts:
  ...  - Should Be Equal: established that things are equal
```
Sorry, I do not like the idea much because it reveals implementation (= assertion is made using `Should Be Equal`). I would collapse it into
```
  ...  Asserts:
  ...  - things are equal
```
or even free text like
```
  ...  Asserts that things are equal.
```
somewhere in the docs.

**Comment by MoreFamed** [comment]
As was said on the meeting, it is not needed to state default values of arguments in documentation since they are generated already. (Just to not forget it. :))

I like the idea of stating types of arguments, however, when generating docs from library written in Python (should we cover this case?), the types are generated automatically when functions corresponding to KW are annotated. Giving them will be superfluous in such a case.

**Comment by MoreFamed** [comment]
Although we are doing this a very similar way as you suggest and we write
```
  ...  Arguments:
  ...  - ``i_am_an_argument``: some docs of it
  ...  - ``another_argument``: some docs of the another

```
I like the way arguments are described in BuiltIn library or Browser library. They have no their special block with their description but their description is "dissolved" in the "general" documentation of the KW. The rule could then be that every argument must be noted in the documentation. When it will be typed in nonproportional, typewriter font (`i_am_an_argument`) by means of closing it into double back apostrophes, they should be easy to find regardless their position in the text. 

The first approach results (in general) into more lines, sometimes doubles the first part of a documentation and is more formal than the other.

I do not know which one I like more. 😄

**Comment by MoreFamed** [comment]
My vote is for `Arguments` instead of `Args` header.

**Comment by MoreFamed** [comment]
(The last comment of mine today, I promise. 😄) Although this is probably written nowhere, many libraries have the first articles of docs of their KWs consisting of one short sentence describing the KW in a nutshell. The detailed description of the KW, if any, is in following articles, as well as description of the arguments (unless there are just one or two of them which would fit into the mentioned first sentence). I like this approach because I have a clue to the KW after reading the first short sentence of the docs.
